#pragma once
#define  FG FOREGROUND_GREEN
#define  FR FOREGROUND_RED
#define  FB FOREGROUND_BLUE

#define  BG BACKGROUND_GREEN
#define  BR BACKGROUND_RED
#define  BB BACKGROUND_BLUE 


#define BBLACK 0x000